form.blade.phpのバリデーションをContactRequestを用いて実行するように変更
ing-murata/contact-form pull request #22
Opened 2024-12-05 07:11 UTC by ing-murata

form.blade.phpのバリデーションでjsでやっているバリデーションをRequestFormを用いて実行されるように変更をしました。

2024-12-05 07:39 UTC, ing-chiba requested changes

2024-12-05 07:39 UTC, ing-chiba commented on app/Http/Requests/ContactRequest.php
> +            'email' => 'required|email|max:255|regex:/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/',
emailだけで良いと思うけど正規表現でのバリデーションも必要？

2024-12-05 08:59 UTC, ing-murata commented on app/Http/Requests/ContactRequest.php
> +            'email' => 'required|email|max:255|regex:/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/',
emailだけにするとaa@aaでも通れたので一応やっておきました。
この場合はaa@example.comみたいな形にしないと通れないです。 @ing-chiba

2024-12-06 09:50 UTC, ing-murata commented
ここでFoemRequestを初めて使っていて、他のところでもContactRequestを使いたいので時間ある時に問題なければマージしていただけると助かります！ @ing-chiba

2024-12-09 04:25 UTC, ing-chiba approved these changes

2024-12-09 04:25 UTC, merged