問い合わせ通知機能
ing-murata/contact-form pull request #28
Opened 2024-12-06 05:15 UTC by ing-murata

お問合せが送信された時、管理者にメールが届くように設定しました。

2024-12-06 05:16 UTC, ing-chiba commented
@ing-murata 
メールサーバーは何使っている？

2024-12-06 05:25 UTC, ing-murata commented
> @ing-murata メールサーバーは何使っている？
@ing-chiba 
詳しくないのでわからないのですが、SMTPというのを使っていると思います。

MAIL_MAILER=smtp
MAIL_HOST=smtp.mail.me.com
MAIL_PORT=587
MAIL_USERNAME=jetblack5810@icloud.com
MAIL_PASSWORD=dogy-vsiy-jjpd-vfni
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=jetblack5810@icloud.com
MAIL_FROM_NAME="Eito"
（.envファイルより引用）

2024-12-06 09:39 UTC, ing-chiba requested changes

2024-12-06 09:39 UTC, ing-chiba commented on app/Mail/InquiryNotification.php
> +    public function __construct(array $contact)
引数は(Contact $contact)にしよう

2024-12-09 04:24 UTC, ing-chiba approved these changes

2024-12-09 04:24 UTC, merged