sign up機能
ing-murata/contact-form pull request #29
Opened 2024-12-06 08:38 UTC by ing-murata

sign upできるようにして新たな管理者が登録しやすくしました。
一方でsign upすれば誰でも問い合わせ一覧画面を見れてしまうので対策したいと思います。

2024-12-06 09:41 UTC, ing-chiba requested changes

2024-12-06 09:41 UTC, ing-chiba commented on app/Http/Controllers/AuthController.php
> +        // 入力のバリデーションとカスタムメッセージの指定
FormRequestでやる

2024-12-06 09:41 UTC, ing-chiba commented on routes/web.php
> +Route::get('/admin/contact', [App\Http\Controllers\ContactController::class, 'index'])->name('admin.contact.index');
管理者じゃなくてもアクセスできてしまう

2024-12-09 04:25 UTC, ing-chiba requested changes

2024-12-09 04:25 UTC, ing-chiba commented on routes/web.php
> +Route::get('/admin/contact', [App\Http\Controllers\ContactController::class, 'index'])->name('admin.contact.index');
@ing-murata ここ直っていなさそう

2024-12-09 04:26 UTC, ing-chiba commented
コンフリクト解消も一緒にお願いします

2024-12-09 06:34 UTC, ing-murata commented
conflict解消しました

2024-12-09 06:59 UTC, ing-murata commented
誰でもsign upできる状態からログインした後の画面でしたsign upできないように変更しました

2024-12-09 07:53 UTC, ing-chiba approved these changes

2024-12-09 07:53 UTC, merged